#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_heroku="$(heroku --version 2>/dev/null | awk '{print $1}' | cut -d/ -f2 || true)"
  jq -n --arg heroku "$ver_heroku" '{heroku: $heroku}'
}

version "$@"
