#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_heroku="0.0.1"
  jq -n --arg heroku "$ver_heroku" '{heroku: $heroku}'
}

version "$@"
